# Generated by Django 5.0.4 on 2026-03-20 10:38

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dojo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beltprogress',
            options={'ordering': ['user', models.Case(models.When(belt_id='white', then=0), models.When(belt_id='yellow', then=1), models.When(belt_id='blue', then=2), models.When(belt_id='red', then=3), models.When(belt_id='black', then=4), models.When(belt_id='brown', then=5), models.When(belt_id='purple', then=6), models.When(belt_id='gold', then=7), models.When(belt_id='master', then=8), output_field=models.IntegerField())], 'verbose_name': 'Belt Progress', 'verbose_name_plural': 'Belt Progress'},
        ),
        migrations.RemoveConstraint(
            model_name='beltprogress',
            name='unique_user_belt',
        ),
        migrations.RemoveConstraint(
            model_name='factmemory',
            name='unique_user_fact',
        ),
        migrations.RemoveConstraint(
            model_name='userbadge',
            name='unique_user_badge',
        ),
        migrations.AlterField(
            model_name='beltprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='factmemory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge_id',
            field=models.CharField(choices=[('first_correct', 'First Correct'), ('white_belt', 'White Belt'), ('yellow_belt', 'Yellow Belt'), ('blue_belt', 'Blue Belt'), ('red_belt', 'Red Belt'), ('black_belt', 'Black Belt'), ('brown_belt', 'Brown Belt'), ('purple_belt', 'Purple Belt'), ('gold_belt', 'Gold Belt'), ('master_belt', 'Master Belt'), ('perfect_belt', 'Perfect Run'), ('speed_run', 'Speed Run'), ('streak_7', 'Week Warrior'), ('century', 'Century')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='beltprogress',
            unique_together={('user', 'belt_id')},
        ),
        migrations.AlterUniqueTogether(
            name='factmemory',
            unique_together={('user', 'a', 'b')},
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge_id')},
        ),
        migrations.AddIndex(
            model_name='factmemory',
            index=models.Index(fields=['user', 'a', 'b'], name='dojo_factme_user_id_721fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='factmemory',
            index=models.Index(fields=['user', 'seen'], name='dojo_factme_user_id_951b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['user', 'created_at'], name='dojo_traini_user_id_67ad37_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['belt_id', 'created_at'], name='dojo_traini_belt_id_860ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorrequest',
            index=models.Index(fields=['student', 'status'], name='dojo_tutorr_student_6c6436_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorrequest',
            index=models.Index(fields=['tutor', 'status'], name='dojo_tutorr_tutor_i_733145_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'badge_id'], name='dojo_userba_user_id_63ca2b_idx'),
        ),
    ]
