# Generated by Django 5.0.4 on 2026-03-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_assignment_assignmentsubmission_chatmessage_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
