# Generated by Django 5.0.4 on 2026-03-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0004_assignmentsubmission_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_belt_idx',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
