# Generated by Django 5.0.4 on 2026-03-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0008_tutorinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorinterest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tutor Interest', 'verbose_name_plural': 'Tutor Interests'},
        ),
        migrations.AlterField(
            model_name='tutorinterest',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
