# Generated by Django 5.0.4 on 2026-03-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0009_alter_tutorinterest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentsubscription',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsubscription',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('initial', 'Initial Payment'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('refund', 'Refund')], default='initial', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='paymentsubscription',
            index=models.Index(fields=['user', 'status'], name='dojo_paymen_user_id_aec0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsubscription',
            index=models.Index(fields=['trial_ends'], name='dojo_paymen_trial_e_d49429_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsubscription',
            index=models.Index(fields=['end_date'], name='dojo_paymen_end_dat_419fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'status'], name='dojo_paymen_user_id_a118b2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference'], name='dojo_paymen_referen_dbed5f_idx'),
        ),
    ]
