# Generated by Django 5.0.4 on 2026-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0012_parentnotification_parentstudentlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor'), ('admin', 'Admin'), ('parent', 'Parent')], db_index=True, default='student', max_length=10),
        ),
    ]
