# Generated by Django 5.0.4 on 2026-03-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('cbc', 'Kenya CBC'), ('844', 'Kenya 8-4-4'), ('igcse', 'IGCSE/Cambridge')], db_index=True, help_text='Educational curriculum (CBC, 8-4-4, IGCSE)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='curriculum_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade level (e.g., Grade 5, Form 2, Year 10)', max_length=50, null=True),
        ),
    ]
