# Generated by Django 5.0.4 on 2026-03-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dojo', '0014_user_curriculum_user_curriculum_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('cbc', 'Kenya CBC (Competency Based Curriculum)'), ('844', 'Kenya 8-4-4 Curriculum'), ('igcse', 'IGCSE / Cambridge International')], db_index=True, help_text='Educational curriculum (CBC, 8-4-4, IGCSE)', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='dojo_user_email_3f232f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='dojo_user_role_e937aa_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['curriculum', 'grade'], name='dojo_user_curricu_cfd635_idx'),
        ),
    ]
