# Generated by Django 5.0.4 on 2026-04-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0016_curriculum_subject_grade_contentitem_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for parents/guardians', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.curriculum'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.grade'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.subject'),
        ),
    ]
