# Generated by Django 5.0.4 on 2026-04-10 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0017_user_phone_alter_contentitem_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='requires_upload',
            field=models.BooleanField(default=False, help_text='Student must upload a working file to answer this question'),
        ),
        migrations.CreateModel(
            name='StudentAnswerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file (PDF, image, Word document, etc.)', upload_to='quiz_attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('answer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dojo.studentanswerdetail')),
            ],
            options={
                'verbose_name': 'Student Answer Attachment',
                'verbose_name_plural': 'Student Answer Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
