# Generated by Django 5.0.4 on 2026-05-05 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0018_question_requires_upload_studentanswerattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('monthly', 'Monthly'), ('half_yearly', '6 Months'), ('yearly', 'Yearly')], max_length=20, unique=True)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_days', models.IntegerField(help_text='Duration in days')),
                ('is_active', models.BooleanField(default=True)),
                ('savings_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('savings_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['-duration_days'],
            },
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='authorization_code',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='paystack_customer_code',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='subscription_code',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='access_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('initial', 'Initial Payment'), ('renewal', 'Auto Renewal'), ('manual_renewal', 'Manual Renewal'), ('upgrade', 'Plan Upgrade')], default='initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='inactive', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=100)),
                ('paystack_customer_code', models.CharField(blank=True, max_length=100)),
                ('paystack_authorization_code', models.CharField(blank=True, max_length=100)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='dojo.usersubscription'),
        ),
        migrations.CreateModel(
            name='UserTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_type', models.CharField(choices=[('multiplication', 'Multiplication Game (Blue Belt+)'), ('curriculum', 'Curriculum Content (CBC/IGCSE/8-4-4)')], max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Trial',
                'verbose_name_plural': 'User Trials',
                'ordering': ['-start_date'],
            },
        ),
        migrations.DeleteModel(
            name='PaymentSubscription',
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='dojo_usersu_user_id_8b205e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['end_date', 'status'], name='dojo_usersu_end_dat_2dea21_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrial',
            index=models.Index(fields=['user', 'trial_type', 'used'], name='dojo_usertr_user_id_13c3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrial',
            index=models.Index(fields=['end_date'], name='dojo_usertr_end_dat_b0c0bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertrial',
            unique_together={('user', 'trial_type')},
        ),
    ]
